### ISSUE TITLE
Branding feature enhancement

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#33] opened 2022-11-14 15:28 UTC
## Rationale

Meeds Software provides way to setup the platform in a simple way: only the theme, the logo and the name of the platform.
Before allowing admin to setup authentication, we propose to enhance the current branding page with additional items so admin can in a simple way manage the platform branding and not only the colors, logo and the theme.

## 1. Functional requirements
- In a new page called General Settings, review the branding current features for a clearer access to items:
* Explain what the logo and the name are used for
* Precise for what the theme colors will be used
* Add a way to change the favicon

![general settings - global view of branding char](https://user-images.githubusercontent.com/58853195/212841180-3a1b97c7-f798-400c-820c-3f066d6f156d.jpg)

- Propose to the admin a way to customize the authentication pages, and more precisely the left panel characteristics
* the title and the subtitle with a way to add translations for these labels. I can if needed add nothing in this field to not display anything in the left panel or to only display the title, but not the subtitle, etc.
![general settings - add translations](https://user-images.githubusercontent.com/58853195/212841160-1f4f6e0b-9c83-45d6-bc85-f5a67094ec1d.jpg)

* the background with a way to add an image, to crop it, zoom it, rotate it, with the help of a canvas so we can see how it will be displayed

![general settings - change background](https://user-images.githubusercontent.com/58853195/212842850-f67a0921-d09f-4dc8-8a0b-51663e1d1dff.jpg)

* propose an additional theme color setting so that the admin can custom the font-color of the title and subtitle

- Once applied, the change are made and the user can reload the page to check items that have been changed.

> **Precisions**: These new way to add translations and to crop an image should be reusable components

### Security 

The new General Settings page has to be added in `/platform/administrators` navigations. The Branding should be remain modifiable only by members of `/platform/administrators` through the Branding REST endpoint (no change on this permission).

### Extensibility 

The Image Cropper Drawer has to be a re-usable component that should be defined in a dedicated JS & CSS Modules. In fact, to use this component inside a portlet, it has to be imported using :

* `gatein-resources.xml` by importing the dedicated JS Module `imageCropper`
* portlet less by importing the dedicated CSS inside the portlet `@import (css) "/eXoSkin/skin/css/component/ImageCropper/cropper.min.css";`

### Upgradability

The newly introduced page `General Settings` will be added in a new navigation node `generalSettings`. The old navigation page `Branding` will not be used anymore. By using the MOP `importMode` feature, the usage of value `overwrite` will be used to delete the old `Branding` page and import the new one.

the property value can be changed throw the property `exo.social.groups.portalConfig.metadata.importmode`.

### Existing Features

The branding portlet will be removed in favor of this new portlet. Using a new portlet for prenting the branding will not impact existing data like custom site logo or branding colors.

The default favicon path is to define in each installation with a new property: `exo.branding.company.favicon`. The default path of favicon may change thus it can have impact on existing installations with customized favicon. To override and get back to the old favicon path, the newly introduced property has to be defined in `exo.properties`.

The Login title & Subtitle customization has to remain as was defined in Meeds-io/MIPs#29. In fact, the default value has to be `UILoginForm.label.pageTitle` & `UILoginForm.label.pageSubTitle` with the possibility to redefine it through `exo.properties` with properties `portal.authentication.title` & `portal.authentication.subtitle` for the default `locale-config.xml` language (By default in `en` in product).

### Feature Flags

No feature flag needed

### Other Non Functional Requirements

* Add the possibility to define a default login background image path using property `portal.authentication.background`. The value of this property can be an absolute path or relative path to webapps contexts like `/skin/images/login-background.png` that can be placed in any Portal Extension Addon.

### Third party library

A third party library will be used for Image cropping: https://fengyuanchen.github.io/cropperjs/ (MIT License, version 1.5.13)

### Data and persistence

No change on Data model, the branding properties will remain retrieved and stored using `SettingService` API.

**Comment by srenault-meeds** [comment] 2022-11-14 15:37
Draft for now

**Comment by margondicco** [comment] 2023-01-12 11:52
Hello first bulk of feedbacks

> Add an item regarding authentication display customization so the admin can change the left panel characteristics (background, title and subtitle)

Multilingual for title and subtitle is a must have

> 3. The admin can activate each of this provider by editing them and by entering conf characteristics

- Must have : for OIDC we need others informations : oauth.openid.wellKnownConfigurationUrl; oauth.openid.redirectURL
- Must have : moreover we should add an option to define the capabality to create or not the account after the first login. 
- Nice to have : give the properties that the admin should use to configure the IDM (https://xx.xx.org/portal/openidAuth)
- To be discussed : IMO provision part is not mandatory and what happens if we set up provisioning via LDAP ?


> By default, the email registration is enabled but the admin can also activate an additional way to self-registrate (depending what tool is set in the authentication configuration)

In my opinion it is necessary to provide the possibility (if authorized by the admin) that the user associates his account (created by email) with another authentication mode (LinkedIn for example)



> By default, the email registration is enabled but the admin can also activate an additional way to self-registrate (depending what tool is set in the authentication configuration)

There may be different connection possibilities for different populations

- An intern can connect via OIDC 
- An external user can connect via Google or LinkedIn

IMO, it should be possible to clarify the login page so that the user knows which connection options to choose.

**Comment by srenault-meeds** [comment] 2023-01-12 12:48
Hello, thanks.
Here are some questions to your feedbacks to make sure I understand.

> Must have : moreover we should add an option to define the capabality to create or not the account after the first login.

Don't understand that case.

> Nice to have : give the properties that the admin should use to configure the IDM (https://xx.xx.org/portal/openidAuth)

Do you mean that we help the admin to understand what to configure?

> To be discussed : IMO provision part is not mandatory and what happens if we set up provisioning via LDAP ?

yes, indeed, good point to discuss with @boubaker 

> In my opinion it is necessary to provide the possibility (if authorized by the admin) that the user associates his account (created by email) with another authentication mode (LinkedIn for example)

Yes, we plan to do it by default is same email used. But we should plan to improve this by linking any add. account from the profile for example (part of the linkedin integration IMO)

> IMO, it should be possible to clarify the login page so that the user knows which connection options to choose.

Don't understand this case

**Comment by srenault-meeds** [comment] 2023-01-17 08:10
@margondicco hello, can you please tell us if ok fonc for you?
Thanks

**Comment by margondicco** [comment] 2023-01-17 08:40
Hello go fonc :-) thank you

one thing : can we add a color on the multiingual button when labels have been added in other languages

**Comment by srenault-meeds** [comment] 2023-01-17 11:39
yes

**Comment by boubaker** [comment] 2023-01-17 17:37
Ready for Tech review @rdenarie

**Comment by rdenarie** [comment] 2023-01-18 09:13
> Configurability
In order to re-import the platform/administrators navigation, the importMode overwrite has to be used to delete branding page and add the new generalSettings page. (this change will be applied on Meeds package only, introduced in meeds.war only)

How eXo instance will benefit of the new page ? of the new portlet ?
As I understand, with the current behaviour, eXo will not see the new application ?

@margondicco can you confirm that we (on eXo side) want to remove the Branding Page to the new General Settings Page ?

**Comment by boubaker** [comment] 2023-01-18 09:26
> How eXo instance will benefit of the new page ? of the new portlet ?
> As I understand, with the current behaviour, eXo will not see the new application ?

For Meeds Package, the re-import has been introduced using this change in order to delete old navigation and replace it by new one : 
https://github.com/Meeds-io/meeds/pull/558/files#diff-96e68ade4d1c7c628054574e9417034fef190fe82b941c05dfe20766afb3c009R22-R32

For eXo package, you can choose either re-import groups navigations by introducing the same configuration/property in `digital-workplace` for example, or let it manual for existing installation by using `layout-management` addon, especially that in your custom installations, you may have used `layout-management` features to change/add navigations of groups. It's up to you to choose, here in this MIP, we will just keep it optional without forcing the re-import.

BTW, another impact to consider for you, is the favicon, its default path, as described above, has changed, if you want to change the default path you can define a another default value too in `digital-workplace` customization.

**Comment by rdenarie** [comment] 2023-01-18 09:49
As I understand, if we do nothing, we will have 2 pages : Branding and General Settings in /platform/administrators navigation.
Can you confirm ?

In addition, I'm not sure to understand the impact of favicon, and action to do. Can you detail please ?

**Comment by boubaker** [comment] 2023-01-18 10:22
> As I understand, if we do nothing, we will have 2 pages : Branding and General Settings in /platform/administrators navigation.
> Can you confirm ?

Yep, the default `importMode` is set to `merge` https://github.com/Meeds-io/social/blob/develop/extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/social-portal-configuration.xml#L171

for Meeds packages, knowing that we don't have `layout management UI`, we turned it into `overwrite` (For Meeds only, eXo packages **deletes** `meeds.war`) https://github.com/Meeds-io/meeds/blob/develop-meed/webapps/plf-meeds-extension/src/main/webapp/META-INF/exo-conf/configuration.xml#L28

The old Branding Portlet (and navigation) has been deleted in favor of new Portlet & page, so an action has to be made in eXo to manually delete Branding page for existing installations or enable `overwrite` mode to deleting Branding Page in existing installations.

> In addition, I'm not sure to understand the impact of favicon, and action to do. Can you detail please ?

As described in spec tech part :

> The default favicon path is to define in each installation with a new property: exo.branding.company.favicon. The default path of favicon may change thus it can have impact on existing installations with customized favicon. To override and get back to the old favicon path, the newly introduced property has to be defined in exo.properties.

In eXo package, you redefine the branding service https://github.com/exoplatform/platform-private-distributions/blob/develop/plf-enterprise-welcome-screens-webapp/src/main/webapp/WEB-INF/conf/welcome-screen/branding-configuration.xml, you will just need to improve it to add the new default configurations introduced in BrandingService https://github.com/Meeds-io/gatein-portal/blob/develop-meed/web/portal/src/main/webapp/WEB-INF/conf/branding/branding-configuration.xml#L5-L54 (default Favicon path, default login background path, default authentication.title & subtitle ...)

**Comment by rdenarie** [comment] 2023-01-18 10:30
Ok for the part about branding service.

But, for the part about configuration, it is not possible to plan a MANUAL steps for updating the branding page. When a customer (hosted by eXo or hosted by himself) is upgraded, we cannot plan a manual step. The update should be transparent for him.
Your modification should make necessary steps to remove Branding page, and add the new one, automatically, without manual step between versions

**Comment by boubaker** [comment] 2023-01-18 12:01
> Your modification should make necessary steps to remove Branding page, and add the new one, automatically, without manual step between versions

Yep, for Meeds context, the importMode `overwrite` is sufficient, especially that this is about administration navigations only. If you have modifications made on administration navigations using your addon `layout-management` on some existing installations, you may handle it manually if you need, but I prefer to avoid an over-engineering stuff for Meeds context for now and blocking this MIP because of that. It may be a purpose of another MIP that you can issue IMO.

@srenault-meeds @plamarque WDYT ?

**Comment by rdenarie** [comment] 2023-01-18 12:38
> > Your modification should make necessary steps to remove Branding page, and add the new one, automatically, without manual step between versions
> 
> Yep, for Meeds context, the importMode `overwrite` is sufficient, especially that this is about administration navigations only. If you have modifications made on administration navigations using your addon `layout-management` on some existing installations, you may handle it manually if you need, but I prefer to avoid an over-engineering stuff for Meeds context for now and blocking this MIP because of that. It may be a purpose of another MIP that you can issue IMO.
> 
> @srenault-meeds @plamarque WDYT ?

In fact, it is not a question of "overriding", but a question of upgrading. We did not made modification on the branding page in layout-management, but we have customers which already have this page. 
It is not possible to deliver something which add a new "branding" page, without removing the old one. The "Upgrade" part is a non functionnal requirement which should be addressed in the feature.

**Comment by boubaker** [comment] 2023-01-18 12:42
Yep, you can make it by using importMode=OVERWRITE which will update the administration navigations by deleting the old one. If you mean that we should have a dedicated framework that should allow to fine-select changes to make by version + per page, this can be adressed in another feature. But, until now, the administration groups navigations update (addin or deleting) was adressed by using the importMode configuration only.

Until, we take time to make things evolve technically, we shouldn't change here the way that we update administration navigations, which means, simply using importMode option.

**Comment by boubaker** [comment] 2023-01-18 12:46
> was adressed by using the importMode configuration only

The question is why changing now ? And why specifically for this MIP ?

**Comment by rdenarie** [comment] 2023-01-18 12:47
In this case, why putting the default mode only on meeds side ?

My gap is that your feature, in is actual state require a manual step OR require a duplication of a configuration you add only in meeds side. 
To apply the new page, we need the same configuration (as you said, currently there is no other way). So why not putting the configuration in a common place ?

**Comment by boubaker** [comment] 2023-01-18 12:58
> To apply the new page, we need the same configuration (as you said, currently there is no other way). So why not putting the configuration in a common place ?

To not force the importMode in common package and let you choose, as said, either to use the `OVERWRITE` mode or Manual mode. Besides, it was placed in Meeds because, that the value is what we want to have all time, not because of this MIP only, but because we don't have 'Layout Management' UI and thus, the old group navigations that we delete by code will remain on production and will not evolve switch our need. But, for your part, the need of using `OVERWRITE` mode is different, which is just for upgrade purpose. That's why you should redefine it in your package and delete it then, when navigations re-imported in a 6.4.1 by example.

**Comment by rdenarie** [comment] 2023-01-18 13:02
> That's why you should redefine it in your package and delete it then, when navigations re-imported in a 6.4.1 by example.

In fact, as a customer can upgrade from 6.3.4 to 6.4.2 in the future, we will not be able to remove the "overwrite" option.

I need to discuss about that point with Morgan. I come back to you here after that

**Comment by srenault-meeds** [comment] 2023-01-18 13:13
Hello, 
I understand your point @rdenarie. We should manage any change in the navigation better. However, as Boubaker as said in comments above (and also during some product committee), we should think deeper about the way we manage navigations update so it is smoothier for any DAO Members.
Currently, as I understand, it is not possible to do this now.

However, for any past upgrades, we (consultant) used to update manually navigation when needed and it wasn't a problem. 
Of course, it would be better to manage this "automatically" but the risk here is not that high, isn't it?
Thanks

**Comment by rdenarie** [comment] 2023-01-18 13:15
> we (consultant) used to update manually navigation when needed and it wasn't a problem.

Yes, and it is always a pain to remember all manual steps to do. So, if possible, I prefer to make it manually.

**Comment by srenault-meeds** [comment] 2023-01-18 13:21
> So, if possible, I prefer to make it manually.

Automatically, do you mean? right?

We usually have a guide to manage upgrades and it is not that painful.
Anyway, if you both, Morgan and you, guess that it is blocker for you, then shouldn't we postpone it to later for the 6.5?

@margondicco I let you comment and tell us what you think.

**Comment by rdenarie** [comment] 2023-01-18 13:32
> Automatically, do you mean? right?

Yes of course, sorry.

> shouldn't we postpone it to later for the 6.5?

No, I prefer to have it now it is finished. I just want to define the upgrade way.

**Comment by rdenarie** [comment] 2023-01-19 08:50
Hello,
After discussion with @margondicco, we think that the overwrite option should be in the common part, not only for meeds. 
We need the new General Setup page, and we need that the old Branding page removed. 

Can you confirm that you can move the overwrite option in commons part ?

Thanks

**Comment by srenault-meeds** [comment] 2023-01-19 09:59
Hello,

Is that blocker for your Go-Tech? 
I mean, for now, we cannot propose PR until we have Go-Tech. So why blocking the MIP delivery only because of that property?
Why not a Go-Tech so that you can test it in your MIPS Acc and so that you can review PR? And then study impacts?

And finally, as the overwrite option can be enabled as a property, why wouldn't you want to add it in your package?
I only want to understand what is blocker here.
Thanks

**Comment by rdenarie** [comment] 2023-01-19 10:06
A Mips is here to speak about requirements, before merging the devs. 
The upgrade gap is a non functionnal requirement we need. I just want to be sure that the feature will be deliver fitting all our requirements (meeds one and eXo one). In the current state, it seems not taken in account, so yes, it is blocker for us.

**Comment by boubaker** [comment] 2023-01-19 10:42
> The upgrade gap is a non functionnal requirement we need. I just want to be sure that the feature will be deliver fitting all our requirements (meeds one and eXo one). In the current state, it seems not taken in account, so yes, it is blocker for us.

I think that it's not blocker since you can make the choice of the flag value in your extensions. I don't want to make it forced to `overwrite` all time. The adaptation to make in your custom developments is very simple, here is the code snippet :

https://github.com/exoplatform/digital-workplace/commit/c94ee34992a10557f3d474f0385ab40d512218ea#diff-d475cfd7b3ba1d0f9f39719ede474a5e0511c044ed63083ba8a20bbc499adda3R12

To change `EXO_IMPORT_MODE_CHOISE_FORM_ADMIN_GROUPS` by `overwrite`, `merge`, `insert` or `conserve`

As I said the need about this flag value is different for us and we will have to keep it all time with `overwrite` because we don't have Layout Customization made by UI, only by configuration. (We can even have a In-Memory implementation of Pages & Navigations of Portal & Group Sites)

I understand if it wasn't flexible to make the flag default value in your addons, but here its not the case and it's flexible enough to make your own choices in your packages, and even to make it evolve switch your needs. Thus, I don't think that we should force the `overwrite` mode in common package and let you redefine it as you wish it to be specifically to your needs.

Thanks for your understanding and proposal.

**Comment by boubaker** [comment] 2023-01-23 15:21
The section `Configurability` has been replace by `Upgradability` to make the title more clear about `Upgradability` requirements.

**Comment by rdenarie** [comment] 2023-01-23 15:32
Go tech added

**Comment by boubaker** [comment] 2023-01-24 07:11
PRs ready to review @rdenarie (added as links of the MIP)

https://github.com/Meeds-io/social/pull/2220
https://github.com/Meeds-io/platform-ui/pull/609
https://github.com/Meeds-io/gatein-portal/pull/526
https://github.com/Meeds-io/meeds/pull/585

**Comment by rdenarie** [comment] 2023-01-24 17:14
I start looking at PRs.

I test a local fresh instance : meeds-1.4.x-mips-SNAPSHOT, and I have a problem : 
pages spaces, people are not present.
Page stream is visible in navigation but display this : 
![image](https://user-images.githubusercontent.com/807839/214361308-9bebbd87-2005-4505-b727-aad0a274cec3.png)

I reproduce with meeds-1.4.x-meed-SNAPSHOT. 
I also reproduce with exo build : plf-6.4.x-mips-SNAPSHOT

**Comment by boubaker** [comment] 2023-01-25 07:00
> I reproduce with meeds-1.4.x-meed-SNAPSHOT.

Not related to current MIP#33 but to the issue https://github.com/Meeds-io/meeds/issues/564 which configures a proper `importMode` to profile page. Fixed anyway for the issue #564. Thanks for having reported this issue.

**Comment by rdenarie** [comment] 2023-01-25 10:40
All PRs are approved, you can merge

**Closed as completed** 2023-01-25 11:25 UTC
Labels: Go - tech, Go - func, Dev done, Login

**Comment by boubaker** [comment] 2023-01-25 11:26
Merged on develop
