### ISSUE TITLE
People Search

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/MIPs#39] opened 2022-12-01 15:23 UTC
## Rationale
It is hard to search for people in the search.

### **Quick search**
Simplify the people search algorithm and make it as the following:

1. When a platform user types a single keyword in the search filed

- the search is launched 300 ms after the typing is stopped
- search results should contain users having the keyword in their display name (composed of first and last names)
- for example, if I set "aul" in the search field, results should display these users "Paul dupont", "Pauline Pauline", "John Paulo", "aulerie james"

2. When a user types a composed keyword in the search field
- the search is launched 300 ms after the typing is stopped
- search results should contain users having the keyword in their display name (composed of first and last names)
- the relation of search of the keywords is AND i.e.: for example, if I set "Paul Dupont" in the search field, results should display these users "Paul Dupont", "Paul Dupont Abreu", "Paul Dupontalon"

3. When a user types a keyword with accented characters
- the search should find results with the accented character and those without accents
- for example, the keyword is Mé, results should contain Meriem Zo, Mélanie, Mèlissa Auguste, Amèlie Mérie, Jaques timés

### **Advanced search**
A new filter button is to be added on people page which opens a drawer with these details:
**Header**: Filter people list
**Body**:
Lists ALL the active profile fields defined by the admin in the profile settings table. Each field has a placeholder which is the profile's attribute Label in the user language, if it does not exist, the attribute name is displayed.
- should respect the defined order in the settings
- fields' names should have the labels of the current selected user language and defined in the settings page
- fields of the advanced search drawer:
  - Field1: full name: text field and the quick search algorithm is applied on
  - First name
  - Last name
  - Field2: email: same behavior as display name search
  - Field3: Job title: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected = OR
  - Field4: Organization: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected = OR
  - Field5: Location: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected = OR
  - Field6: Department: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected =OR
  - Field7: Team: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected =OR
  - Field8: Job: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected =OR
  - Field9: Country: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected =OR
  - Field10: City: text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected =OR
  - Field11: Phone: text field and the quick search algorithm is applied on i.e. it searches the numbers typed in the same order
  - custom fields  text field with suggestions that could be selected, multiple selection is allowed. Search rules if 2 informations are selected = OR

Search rules between two fields : AND

I search TEAM = Devsquad and POSITION = Techlead
the result is only users who are in the DEVSQUAD team AND the TECHLEAD position

**Footer**: Cancel and confirm buttons, Reset link allowing to clear all selected choices
Link to design https://xd.adobe.com/view/67af9e11-4e0d-4d70-98a1-7dd0150b0cb0-32fc/

Confirm button launches the search
Cancel closes the drawer and empties the drawer
when i click outside the drawer or the cross icon in the drawer's header, the drawer closes but when reopen it, it is filled 
A page load clear the different choice and displays the whole people list

**Another functional requirements**

the URL contains the search criteria :
example from the unified search : search?q=&types=&favorites=true&tags=holders,Renting

Sort order : no change ascendant on last name

**button filters**

The button filter counts the number of selected fields

### Expected Volume & Performance

We should optimize the search for more than 100k results

### Feature Flags

A new feature flag `exo.feature.peopleAdvancedFilter.enabled` should be used to enable/disable the advanced filter Button:
Property Name: `exo.feature.peopleAdvancedFilter.enabled`
Default Value: False, to hide the feature until fully implemented
Target Audience: Platform users
Functional Behavior: hides the advanced search button when set to false, displays the advanced search button when set to true
After developments end, the Feature Flag will be removed, and the feature will be usable by eXo and Meeds

### Documentation 

New note: Add documentation about the people advanced search
Describe how the quick search functions 

### Access 
**- Rest API design:**
/rest/v1/social/users should be updated to get the list of fields on the advanced search.
   **- Portlet** 
A new "Advanced search drawer" to add to the people portlet.

### Services & processing
   - Now search for users is using the social/organization api, this will be really complicated to update that to be able to search for custom fields and to apply all search rules defined here, 
=> In our case, we will need to create a new elastic search connector for users. (all users search)

**Comment by rdenarie** [comment] 2022-12-02 16:53
> It is hard to search for people in the search.

Do you mean "Unified Search" ? or the search field in People Directory ? After looking at the design, I understand it is People Directory

> Feature Flag

Should we remove the FF after development finished ? If not, what will be the feature flag value after development finished ? 

> - Rest API design:

/rest/v1/social/users should be updated to get the list of fields on the advanced search.
the UserRestService get information about users, not about profile settings. The list of field in profile will be provided by a specific REST service developed into feature Profile Settings. 
The /rest/v1/social/users should be updated to be able to add new filter in the search. 
Can you describe how this modification will be made ? Which parameters will be added ? a list of x parameters (x is unknown) ? or a string containing all parameters ? Please describe

> => In our case, we will need to create a new elastic search connector for users. (all users search)

The ProfileSearchConnector make an elastic search. Can you confirm that you will reuse it, and not add a new search connector ?

> Other questions :

Do you need to index some new properties in profile ? 
Do we really need all profile informations in this drawer ? It make it very huge. For example, do you ever search someone by his phone number ?


cc @mzorai @mkrout @azayati 
Thanks for your answers

**Comment by mzorai** [comment] 2022-12-05 10:32
@rdenarie thanks for feedback

>Do you mean "Unified Search" ? or the search field in People Directory ? After looking at the design, I understand it is People Directory

The quick search in People directory, currently it searches in all fields, we want to search only on display names (first and last names)

> Should we remove the FF after development finished ? If not, what will be the feature flag value after development finished ?

Yes we'll have a feature flag for the advanced search feature until it is done and validated. When everything is OK we'll set the feature flag to true (i.e. enable the people advanced search drawer display)

> Do we really need all profile informations in this drawer ? It make it very huge. For example, do you ever search someone by his phone number ?

I'd proposed to make only visible fields searchable through the advanced search drawer but looks like we need all fields. Yes it is rare to search for a user using his phone number but it still a use case (when I only have his number, he already called me and that I need to search his profile for more details) cc @margondicco

**Comment by srenault-meeds** [comment] 2022-12-05 11:13
Hi,

Thanks for this MIP :-)
My feedbacks:

> It is hard to search for people in the search.

Can you please add more precision? How do you know it is hard? What is the problem we are trying to solve? Which search is taken here (unified or people)? Is that hard because name are not indexed, because sorting is not understandable, because we can't search on all profile informations, because the search card in results page are not easy to read, not easy to access?

> for example, if I set "aul" in the search field, results should display these users "Paul dupont", "Pauline Pauline", "John Paulo", "aulerie james"

Do we plan to also take into account wrong search by helping the user? I mean, we can with ES make possible to get results when I type OAUL, then it proposes you Paul

> the relation of search of the keywords is AND i.e.: for example, if I set "Paul Dupont" in the search field, results should display these users "Paul Dupont", "Paul Dupont Abreu", "Paul Dupontalon"

Do you plan to list result like Paul Abreu Dupont? 

> Other point that seems missing to me IMO

It could be more than interesting to offer a better UX when searching. For example, as you might know, we can build a network by connecting to other people. Then that would be nice to list results the following way:
1. matching result from my network
2. matching result outside my network
Of course with an information to the user so it is easy to get that sorting.

In addition (maybe in the future), we could have more behaviour like that:
1. my network
2. latest seen profile, latest interaction with
3. others

That way, when I have lots of people with same name or same first name (which is more accurate), then I have firstly the contact I am looking for.
Example: when you search for Julien, then because you discuss more with Julien Dubois (our coworker), you have him in the first result and then others.

> Advanced search

We miss the behaviour that we should have when multiple filters to be applied so it is clear to the user who is about to confirm the filtering and so it is possible to adjust the filtering.
We thought about this before there: https://xd.adobe.com/view/d5d21e8e-65c1-4f00-99c3-48aa54b9218f-8081/screen/2fbf50f7-6d0a-4a44-9cd3-a2831f061e35/

But maybe a better UX would be reminded the filters applied above the result and then the user can remove filters from there without going to advanced filters options.

> Advanced search

- Do we agree that only when confirming, then results are refreshed?

> Footer / bottom bar of the drawer

How do you manage the closing of the drawer? Do you plan to remove the filters applied even if not confirmed? Or do you plan to let them selected without applying the search so I can go back to the drawer if needed? That way, I can by mistake close outside and I don't lose my choices. Until of course i reload the page itself.

> Results

Can you please make sure that results are "linked" so if needed I can copy the link of results and share it to people so they can access the results I want them to look?


Thanks

**Comment by rdenarie** [comment] 2022-12-05 13:32
> > Should we remove the FF after development finished ? If not, what will be the feature flag value after development finished ?
> 
> Yes we'll have a feature flag for the advanced search feature until it is done and validated. When everything is OK we'll set the feature flag to true (i.e. enable the people advanced search drawer display)

After developments, will we set the FF to true ? or will we remove it at all ?

> I'd proposed to make only visible fields searchable through the advanced search drawer but looks like we need all fields

I don't understand why we need all fields. The drawer is enormous in the design, and contains a lot of fields which will be never user 99% of the time. I think we should simplify a little

**Comment by margondicco** [comment] 2022-12-13 08:28
@rdenarie @mzorai @Samuel-Renault-eXo @plamarque @mkrout 
Functional part updated after the last Meeds product comitee

**Comment by rdenarie** [comment] 2022-12-21 16:38
@boubaker PR ready for tech review

**Comment by boubaker** [comment] 2022-12-22 04:53
> @boubaker PR ready for tech review

There is no PR yet, right ? Is it just a tech review which is needed ?

**Comment by rdenarie** [comment] 2022-12-22 09:17
Yes sorry, only tech review

**Comment by boubaker** [comment] 2023-01-06 13:58
> the search is launched 300 ms after the typing is stopped

The delay already exists, why redefining it here as it was new ?

> After developments, will we set the FF to true ? or will we remove it at all ?

No need to a Feature Flag IMO. It should be used wisely and only sometimes where end users can benefit from it. (waste of time of dev, test & code maintainability & complexity)

> In our case, we will need to create a new elastic search connector for users. (all users search)

It's maybe time to introduce the elasticsearch client using Spring Object Mapping as well : https://www.baeldung.com/spring-data-elasticsearch-tutorial

**Comment by mkrout** [comment] 2023-01-09 11:05
> The ProfileSearchConnector make an elastic search. Can you confirm that you will reuse it, and not add a new search connector ?
> 
> >

We will reuse the existing ES connector, no need to create a new one

**Comment by rdenarie** [comment] 2023-01-09 12:41
Ok
@boubaker can you give a gotech if it is ok ?

**Comment by srenault-meeds** [comment] 2023-01-16 08:27
Hello @margondicco @mzorai 

How would you deal with the mobile view of the search?
Indeed, we plan to enhance the mobile view of people and members app in a space the following way:


![Image](https://user-images.githubusercontent.com/58853195/212631496-12c66006-89bc-410e-8720-c2f8e30ca606.png)



![Image](https://user-images.githubusercontent.com/58853195/212631523-7bbf36a6-6989-4aa6-aed9-5da3d033cd13.png)



Another question: would this search be enabled as well when searching members in a space?
Thanks

**Comment by mzorai** [comment] 2023-01-19 14:44
> Hello @margondicco @mzorai
> 
> How would you deal with the mobile view of the search? Indeed, we plan to enhance the mobile view of people and members app in a space the following way:


We'll display search results the same as currently, we didn't work on a mobile design, we'll just add the advanced search button

> Another question: would this search be enabled as well when searching members in a space? Thanks


The advanced search drawer is planned to be added into "People" page. We didn't planned to add it to members app in a space.

**Comment by azayati** [comment] 2023-01-31 13:12
PRs review needed:

- https://github.com/Meeds-io/social/pull/2191

@boubaker @rdenarie

**Comment by boubaker** [comment] 2023-02-01 08:25
Needs https://github.com/Meeds-io/MIPs/issues/38 to be reviewed since this MIP uses some components defined in #38

**Comment by boubaker** [comment] 2023-02-13 16:33
PRs of #38 approved, @rdenarie it's ok for merge this one after #39

**Closed as completed** 2023-02-14 10:06 UTC
Labels: Go - tech, Go - func, Dev done
